name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          
      - name: Build binaries
        run: make build-all
        
      - name: Create archives
        run: |
          tar -czvf goload-linux-amd64.tar.gz -C dist/linux goload
          tar -czvf goload-darwin-amd64.tar.gz -C dist/darwin goload
          zip -j goload-windows-amd64.zip dist/windows/goload.exe
          sha256sum goload-*.tar.gz goload-*.zip > checksums.txt
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            goload-linux-amd64.tar.gz
            goload-darwin-amd64.tar.gz
            goload-windows-amd64.zip
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}